export enum QueryParameterKey {
  eX = 'eX',
  eY = 'eY',
  eZ = 'eZ',
  bX = 'bX',
  bY = 'bY',
  bZ = 'bZ',
  vR = 'vR',
  uR = 'uR',
  vPhi = 'vPhi',
  uPhi = 'uPhi',
  vTheta = 'vTheta',
  uTheta = 'uTheta',
  showComps = 'showComps',
  showS = 'showS',
  showU = 'showU',
  showF = 'showF',
  showA = 'showA',
  hideV = 'hideV',
  hideEandB = 'hideEandB',
  q = 'q',
  m = 'm',
}
